# The URL the site will be built for
base_url = "//archie-zola.vercel.app/" 
generate_feed = true
title = "jenny coffee blog"
description = "e"
compile_sass = true
build_search_index = true

taxonomies = [
    { name = "tags" }
]

default_language = "en"

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]

# control dark mode: auto | dark | toggle
mode = "toggle"
useCDN = true
favicon = "/icon/favicon.png"
copyright = "maesoser"

# [extra.translations]
# languages = [ {name = "en", url = "/"} ]

[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "Home", url = "/", weight = 2 },
    { name = "All posts", url = "/posts", weight = 2 },
    { name = "About", url = "/about", weight = 3 },
    { name = "Reading", url = "/reading", weight = 4 },
    { name = "Tags", url = "/tags", weight = 5 },
]
